# Generated by Django 5.1.15 on 2026-04-28 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_employee_stats_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeestatssnapshot',
            new_name='analytics_e_employe_3d1372_idx',
            old_name='analytics_e_employe_8a1b2c_idx',
        ),
    ]
