# Generated by Django 5.1.7 on 2026-03-07 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nazwa')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Kod producenta lub wewnętrzny', max_length=80, verbose_name='kod / SKU')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cena zakupu')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, help_text='Domyślna cena przy wycenie', max_digits=10, verbose_name='cena sprzedaży')),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stan magazynowy')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Próg do zamówienia / alertu', max_digits=10, verbose_name='stan minimalny')),
                ('unit', models.CharField(default='szt.', max_length=20, verbose_name='jednostka')),
                ('category', models.CharField(blank=True, help_text='np. ekrany, baterie, obudowy', max_length=80, verbose_name='kategoria')),
                ('notes', models.TextField(blank=True, verbose_name='notatki')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
            ],
            options={
                'verbose_name': 'część',
                'verbose_name_plural': 'części',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nazwa')),
                ('nip', models.CharField(blank=True, max_length=20, verbose_name='NIP')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='ulica')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='miasto')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='kod pocztowy')),
                ('country', models.CharField(blank=True, default='Polska', max_length=100, verbose_name='kraj')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('notes', models.TextField(blank=True, verbose_name='notatki')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
            ],
            options={
                'verbose_name': 'dostawca',
                'verbose_name_plural': 'dostawcy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ilość')),
                ('unit_price_used', models.DecimalField(decimal_places=2, help_text='Cena po której sprzedano (może różnić się od ceny katalogowej)', max_digits=10, verbose_name='cena jedn. zastosowana')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notatka')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.part', verbose_name='część')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='repairs.repairrequest', verbose_name='naprawa')),
            ],
            options={
                'verbose_name': 'użycie części',
                'verbose_name_plural': 'użycia części',
                'ordering': ['repair', 'part'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='numer zamówienia')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłane'), ('confirmed', 'Potwierdzone'), ('partially_received', 'Częściowo dostarczone'), ('received', 'Dostarczone'), ('cancelled', 'Anulowane')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('ordered_at', models.DateTimeField(blank=True, null=True, verbose_name='data zamówienia')),
                ('expected_at', models.DateField(blank=True, null=True, verbose_name='oczekiwana dostawa')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='data dostawy')),
                ('notes', models.TextField(blank=True, verbose_name='notatki')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='utworzone przez')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.supplier', verbose_name='dostawca')),
            ],
            options={
                'verbose_name': 'zamówienie zakupu',
                'verbose_name_plural': 'zamówienia zakupu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ilość')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena jedn.')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='zamówienie')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.part', verbose_name='część')),
            ],
            options={
                'verbose_name': 'pozycja zamówienia',
                'verbose_name_plural': 'pozycje zamówienia',
                'ordering': ['order', 'part'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier', verbose_name='dostawca'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['code'], name='inventory_p_code_78998b_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='inventory_p_categor_1f4e89_idx'),
        ),
    ]
