# Generated by Django 6.0.2 on 2026-03-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partusage',
            name='blocks_repair',
            field=models.BooleanField(default=True, help_text='Czy brak tej części blokuje realizację naprawy', verbose_name='blokuje naprawę'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='order_status',
            field=models.CharField(blank=True, choices=[('to_order', 'Do zamówienia'), ('ordered', 'Zamówione'), ('arrived', 'Dotarło'), ('delayed', 'Opóźnione')], db_index=True, default='to_order', max_length=20, verbose_name='status zamówienia'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data zamówienia'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_parts', to=settings.AUTH_USER_MODEL, verbose_name='zamawiający'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_usages', to='inventory.purchaseorder', verbose_name='zamówienie zakupu'),
        ),
    ]
