# Generated by Django 6.0.2 on 2026-03-08 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_part_usage_order_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='marka'),
        ),
        migrations.AddField(
            model_name='part',
            name='device_category',
            field=models.CharField(blank=True, choices=[('phone', 'Telefon'), ('tablet', 'Tablet'), ('smartwatch', 'Smartwatch'), ('laptop', 'Laptop'), ('desktop', 'Komputer stacjonarny'), ('printer', 'Drukarka'), ('console', 'Konsola'), ('data_recovery', 'Odzyskiwanie danych'), ('other', 'Inne')], db_index=True, help_text='np. telefon, laptop', max_length=30, verbose_name='kategoria urządzenia'),
        ),
        migrations.AddField(
            model_name='part',
            name='device_model_name',
            field=models.CharField(blank=True, db_index=True, help_text='np. iPhone 13, ThinkPad T480', max_length=150, verbose_name='model urządzenia'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.CharField(blank=True, db_index=True, help_text='np. LCD, bateria, matryca, toner', max_length=80, verbose_name='typ części'),
        ),
        migrations.AddField(
            model_name='part',
            name='quality_variant',
            field=models.CharField(blank=True, db_index=True, help_text='np. oryginał, zamiennik', max_length=40, verbose_name='wariant jakości'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_part_usages', to=settings.AUTH_USER_MODEL, verbose_name='dodał'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cena za którą kupiono', max_digits=10, null=True, verbose_name='koszt zakupu (jedn.)'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_usages', to='inventory.supplier', verbose_name='hurtownia'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='usage_status',
            field=models.CharField(choices=[('ordered', 'Zamówiona'), ('arrived', 'Dotarła'), ('used', 'Użyta w naprawie'), ('unused', 'Niewykorzystana')], db_index=True, default='ordered', max_length=20, verbose_name='status części'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='link do hurtowni'),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(blank=True, help_text='np. ekrany, baterie, obudowy', max_length=80, verbose_name='kategoria wewnętrzna'),
        ),
        migrations.AlterField(
            model_name='part',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notatka wewnętrzna'),
        ),
        migrations.AlterField(
            model_name='part',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cena zakupu (ostatnia/domyślna)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.supplier', verbose_name='dostawca domyślny'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='unit_price_used',
            field=models.DecimalField(decimal_places=2, help_text='Cena po której sprzedano klientowi', max_digits=10, verbose_name='cena jedn. zastosowana'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notatka wewnętrzna'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['device_category', 'brand', 'device_model_name'], name='inventory_p_device__1913ce_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['part_type', 'quality_variant'], name='inventory_p_part_ty_9d6746_idx'),
        ),
    ]
