# Generated by Django 5.1.15 on 2026-03-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_average_delivery_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='partusage',
            name='expected_arrival_date',
            field=models.DateField(blank=True, help_text='Kiedy część ma dotrzeć do serwisu (orientacyjnie)', null=True, verbose_name='planowana data dostawy'),
        ),
    ]
