# Generated by Django 5.1.15 on 2026-03-28 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_partusage_expected_arrival_date'),
        ('repairs', '0020_partusage_custom_part_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partusage',
            options={'ordering': ['repair', 'id'], 'verbose_name': 'użycie części', 'verbose_name_plural': 'użycia części'},
        ),
        migrations.AddField(
            model_name='partusage',
            name='custom_part_name',
            field=models.CharField(blank=True, default='', help_text='Gdy brak pozycji w katalogu: dowolna nazwa wpisana w naprawie.', max_length=200, verbose_name='nazwa własna (bez katalogu)'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='part',
            field=models.ForeignKey(blank=True, help_text='Pozycja z katalogu — albo puste, gdy używana jest wyłącznie nazwa własna.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='inventory.part', verbose_name='część'),
        ),
        migrations.AddConstraint(
            model_name='partusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('part__isnull', False), ('custom_part_name', '')), models.Q(('part__isnull', True), models.Q(('custom_part_name', ''), _negated=True)), _connector='OR'), name='inventory_partusage_part_xor_custom_name'),
        ),
    ]
