import type { Config } from "tailwindcss";

/** PRO-KOM premium: primary #e11d1d, dark #0f0f0f, neutral #6b7280 */
const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/(public)/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./sections/**/*.{js,ts,jsx,tsx,mdx}",
    "./features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      screens: {
        xs: "400px",
        zgl: "860px",
      },
      colors: {
        primary: "#e11d1d",
        dark: "#0f0f0f",
        neutral: "#6b7280",
        prokom: {
          white: "#ffffff",
          black: "#0f0f0f",
          accent: "#e11d1d",
          gray: "#6b7280",
          success: "#16a34a",
          warning: "#ea580c",
          error: "#dc2626",
          info: "#2563eb",
        },
        zgl: {
          red: "#e02020",
          "red-h": "#c51a1a",
          "red-glow": "rgba(224,32,32,.25)",
          "red-l": "rgba(224,32,32,.10)",
          "red-border": "rgba(224,32,32,.30)",
          dark: "#0b0c10",
          dark2: "#11131a",
          card: "#171921",
          card2: "#1c1f28",
          card3: "#21252f",
          white: "#ffffff",
          ink: "#cdd0d8",
          ink2: "#9ba3b0",
          muted: "#5c6474",
          faint: "#2e323d",
          border: "rgba(255,255,255,.065)",
          border2: "rgba(255,255,255,.11)",
          "border-r": "rgba(224,32,32,.28)",
        },
        zglf: {
          red: "#dc1e1e",
          "red-h": "#b81818",
          "red-l": "rgba(220,30,30,.08)",
          "red-m": "rgba(220,30,30,.18)",
          "red-glow": "rgba(220,30,30,.35)",
          "red-border": "rgba(220,30,30,.25)",
          bg: "#f2f2f0",
          white: "#ffffff",
          border: "#e4e4e2",
          border2: "#cecece",
          field: "#f7f7f5",
          text: "#111111",
          text2: "#4a4a4a",
          muted: "#9a9a9a",
          divider: "#ebebea",
          sdark: "#0a0b0f",
          scard: "#14161d",
          scard2: "#1a1d26",
          scard3: "#20242f",
          sink: "#c8cbd4",
          sink2: "#8a93a2",
          smuted: "#4e5669",
          sborder: "rgba(255,255,255,.06)",
          sborder2: "rgba(255,255,255,.10)",
        },
      },
      fontFamily: {
        sans: ["var(--font-dm-sans)", "system-ui", "sans-serif"],
        syne: ["var(--font-syne)", "system-ui", "sans-serif"],
        unbounded: ["var(--font-unbounded)", "system-ui", "sans-serif"],
        "plus-jakarta": ["var(--font-plus-jakarta)", "system-ui", "sans-serif"],
      },
      boxShadow: {
        soft: "0 4px 6px -1px rgb(0 0 0 / 0.07), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
        card: "0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.08)",
      },
      borderRadius: {
        "zgl-card": "22px",
        "zgl-field": "12px",
        "zgl-pill": "9999px",
      },
      keyframes: {
        stepIn: {
          from: { opacity: "0", transform: "translateY(12px)" },
          to: { opacity: "1", transform: "none" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.2" },
        },
        fadeUp: {
          from: { opacity: "0", transform: "translateY(18px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        eyebrowSlide: {
          from: { opacity: "0", transform: "translateX(-12px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        stepSlide: {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        stepSlideBack: {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        ringPulse: {
          "0%": { boxShadow: "0 0 0 0 rgba(220,30,30,.35)" },
          "70%": { boxShadow: "0 0 0 10px rgba(220,30,30,0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(220,30,30,0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        dotPop: {
          "0%": { transform: "scale(0)" },
          "65%": { transform: "scale(1.3)" },
          "100%": { transform: "scale(1)" },
        },
        checkPop: {
          "0%": { transform: "scale(0) rotate(-10deg)" },
          "60%": { transform: "scale(1.2) rotate(3deg)" },
          "100%": { transform: "scale(1) rotate(0)" },
        },
        successBounce: {
          "0%": { opacity: "0", transform: "scale(.6) translateY(10px)" },
          "60%": { transform: "scale(1.05) translateY(-4px)" },
          "100%": { opacity: "1", transform: "scale(1) translateY(0)" },
        },
        ring: {
          "0%": { transform: "scale(0.8)", opacity: "0.55" },
          "100%": { transform: "scale(2.2)", opacity: "0" },
        },
        scaleX: {
          "0%": { transform: "scaleX(0)" },
          "100%": { transform: "scaleX(1)" },
        },
        lineGrow: {
          from: { transform: "scaleX(0)" },
          to: { transform: "scaleX(1)" },
        },
      },
      animation: {
        "step-in": "stepIn 0.28s ease both",
        "step-slide": "stepSlide 0.3s ease both",
        "step-slide-back": "stepSlideBack 0.3s ease both",
        "fade-in": "fadeIn 0.3s ease both",
        "eyebrow-slide": "eyebrowSlide 0.5s ease both",
        "ring-pulse": "ringPulse 2s ease infinite",
        "ring-pulse-delay": "ringPulse 2.5s 1s ease infinite",
        shimmer: "shimmer 3s linear infinite",
        "dot-pop": "dotPop 0.3s cubic-bezier(.34,1.56,.64,1) both",
        "check-pop": "checkPop 0.3s cubic-bezier(.34,1.56,.64,1) both",
        "success-bounce": "successBounce 0.6s cubic-bezier(.34,1.4,.64,1) both",
        float: "float 4s ease-in-out infinite",
        blink: "blink 1.6s infinite",
        fadeUp: "fadeUp 0.7s ease both",
        "fade-up": "fadeUp 0.55s ease both",
        "fade-up-d": "fadeUp 0.55s 0.12s ease both",
        ring: "ring 1.4s ease-out infinite",
        scaleX: "scaleX 0.8s ease both",
        "line-grow": "lineGrow 0.3s ease forwards",
      },
    },
  },
  plugins: [],
};

export default config;
