# Generated by Django 5.1.7 on 2026-03-07 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0004_add_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(blank=True, verbose_name='wyniki diagnostyki')),
                ('recommendation', models.TextField(blank=True, help_text='Proponowane działania / wycena', verbose_name='rekomendacja')),
                ('risk_note', models.TextField(blank=True, verbose_name='uwaga o ryzyku')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='data zakończenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports', to=settings.AUTH_USER_MODEL, verbose_name='wykonał')),
                ('repair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_report', to='repairs.repairrequest', verbose_name='naprawa')),
            ],
            options={
                'verbose_name': 'raport diagnostyczny',
                'verbose_name_plural': 'raporty diagnostyczne',
            },
        ),
    ]
