# Generated by Django 5.1.7 on 2026-03-07 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0004_add_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='akcja')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='typ obiektu')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='id obiektu')),
                ('change_payload', models.JSONField(blank=True, default=dict, verbose_name='zmiany')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to='repairs.repairrequest', verbose_name='naprawa')),
            ],
            options={
                'verbose_name': 'wpis audytu',
                'verbose_name_plural': 'wpisy audytu',
                'ordering': ['-created_at'],
            },
        ),
    ]
