# Generated by Django 5.1.7 on 2026-03-07 21:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('repairs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabourType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nazwa')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='domyślna cena')),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, help_text='Do szacowanej daty zakończenia naprawy', null=True, verbose_name='szacowany czas [min]')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
            ],
            options={
                'verbose_name': 'typ robocizny',
                'verbose_name_plural': 'typy robocizny',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kwota')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='data wpłaty')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notatka')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deposits', to=settings.AUTH_USER_MODEL, verbose_name='utworzone przez')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='repairs.repairrequest', verbose_name='naprawa')),
            ],
            options={
                'verbose_name': 'zaliczka',
                'verbose_name_plural': 'zaliczki',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='wersja')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('sent', 'Wysłana'), ('accepted', 'Zaakceptowana'), ('rejected', 'Odrzucona'), ('expired', 'Wygasła')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suma pozycji (aktualizowana przy zapisie)', max_digits=10, verbose_name='suma')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='wysłana')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='ważna do')),
                ('notes', models.TextField(blank=True, verbose_name='notatki do wyceny')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL, verbose_name='utworzone przez')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='repairs.repairrequest', verbose_name='naprawa')),
            ],
            options={
                'verbose_name': 'wycena',
                'verbose_name_plural': 'wyceny',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('item_type', models.CharField(choices=[('part', 'Część'), ('labour', 'Robocizna'), ('other', 'Inne')], db_index=True, max_length=20, verbose_name='typ')),
                ('description', models.CharField(blank=True, help_text='Nazwa pozycji (np. z part/labour lub dowolny tekst)', max_length=300, verbose_name='opis')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='ilość')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena jedn.')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='razem')),
                ('labour_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='pricing.labourtype', verbose_name='typ robocizny')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='inventory.part', verbose_name='część')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.quote', verbose_name='wycena')),
            ],
            options={
                'verbose_name': 'pozycja wyceny',
                'verbose_name_plural': 'pozycje wyceny',
                'ordering': ['quote', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['repair', 'status'], name='pricing_quo_repair__7e4df6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('repair', 'version')},
        ),
    ]
