# Generated by Django 5.1.15 on 2026-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_quoteitem_parts_labour_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Części + robocizna na jednostkę; używane razem z ilością do kwoty pozycji.', max_digits=10, verbose_name='cena jedn. (suma)'),
        ),
    ]
