# Generated by Django 5.1.15 on 2026-03-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_quoteitem_part_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='last_client_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Ustawiane przy udanej wysyłce e-maila z podsumowaniem wyceny.', null=True, verbose_name='ostatnia kopia wyceny na e-mail klienta'),
        ),
    ]
