# Generated by Django 6.0.2 on 2026-03-08 11:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_initial_orders_module'),
        ('inventory', '0003_parts_catalog_and_usage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nazwa')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='marka')),
                ('product_type', models.CharField(blank=True, db_index=True, help_text='np. ładowarka, kabel, etui, szkło', max_length=80, verbose_name='typ produktu')),
                ('notes', models.TextField(blank=True, verbose_name='notatka')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktywny')),
            ],
            options={
                'verbose_name': 'produkt (zamówienia)',
                'verbose_name_plural': 'produkty (zamówienia)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='nazwa kategorii')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktywna')),
            ],
            options={
                'verbose_name': 'kategoria produktów (zamówienia)',
                'verbose_name_plural': 'kategorie produktów (zamówienia)',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='telefon kontaktowy')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail kontaktowy')),
                ('product_name_override', models.CharField(blank=True, help_text='Gdy produkt nie jest z katalogu', max_length=200, verbose_name='nazwa produktu (jeśli nowy)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='ilość')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='cena zakupu')),
                ('sell_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='cena sprzedaży dla klienta')),
                ('planned_order_date', models.DateField(blank=True, null=True, verbose_name='planowana data zamówienia')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='przewidywana data dotarcia')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('to_order', 'Do zamówienia'), ('ordered', 'Zamówione'), ('in_transit', 'W drodze'), ('arrived', 'Dotarło'), ('client_notified', 'Klient poinformowany'), ('ready_for_pickup', 'Gotowe do odbioru'), ('picked_up', 'Odebrane'), ('cancelled', 'Anulowane')], db_index=True, default='new', max_length=30, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notatka')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='zaliczka')),
                ('client_notified', models.BooleanField(default=False, verbose_name='klient poinformowany')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='data odbioru')),
                ('deposit_paid', models.BooleanField(default=False, verbose_name='zaliczka wpłacona')),
                ('urgent', models.BooleanField(default=False, verbose_name='pilne')),
                ('client_waiting', models.BooleanField(default=False, verbose_name='klient czeka')),
                ('requires_contact', models.BooleanField(default=False, verbose_name='wymaga kontaktu')),
                ('overdue', models.BooleanField(default=False, verbose_name='przeterminowane')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='clients.client', verbose_name='klient')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='dodał')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='inventory.supplier', verbose_name='hurtownia')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to='orders.orderproduct', verbose_name='produkt z katalogu')),
            ],
            options={
                'verbose_name': 'zamówienie klienta',
                'verbose_name_plural': 'zamówienia klientów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='orders.orderproductcategory', verbose_name='kategoria'),
        ),
        migrations.CreateModel(
            name='StoreSupplyOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='ilość')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='szacowany koszt')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('standard', 'Standardowy'), ('high', 'Wysoki'), ('urgent', 'Pilne')], db_index=True, default='standard', max_length=20, verbose_name='priorytet')),
                ('status', models.CharField(choices=[('to_order', 'Do zamówienia'), ('ordered', 'Zamówione'), ('in_transit', 'W drodze'), ('arrived', 'Dotarło'), ('restocked', 'Uzupełniono na sklepie'), ('cancelled', 'Anulowane')], db_index=True, default='to_order', max_length=30, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notatka')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_store_supply_orders', to=settings.AUTH_USER_MODEL, verbose_name='dodał')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_supply_orders', to='orders.orderproduct', verbose_name='produkt')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_supply_orders', to='inventory.supplier', verbose_name='hurtownia')),
            ],
            options={
                'verbose_name': 'zaopatrzenie sklepu',
                'verbose_name_plural': 'zaopatrzenie sklepu',
                'ordering': ['-created_at'],
            },
        ),
    ]
