# Generated by Django 5.1.7 on 2026-03-07 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0004_add_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('visit', 'Wizyta'), ('pickup', 'Odbiór'), ('other', 'Inne')], max_length=30, verbose_name='typ')),
                ('event_date', models.DateField(verbose_name='data')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='godzina rozpoczęcia')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='godzina zakończenia')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('is_locked', models.BooleanField(default=False, verbose_name='zablokowane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='pracownik')),
                ('repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='repairs.repairrequest', verbose_name='naprawa')),
            ],
            options={
                'verbose_name': 'wydarzenie kalendarza',
                'verbose_name_plural': 'wydarzenia kalendarza',
                'ordering': ['event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeslotBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField(verbose_name='data')),
                ('start_time', models.TimeField(verbose_name='od godziny')),
                ('end_time', models.TimeField(verbose_name='do godziny')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='powód')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_blocks', to=settings.AUTH_USER_MODEL, verbose_name='pracownik')),
            ],
            options={
                'verbose_name': 'blokada terminu',
                'verbose_name_plural': 'blokady terminów',
                'ordering': ['block_date', 'start_time'],
            },
        ),
    ]
