# Generated by Django 6.0.2 on 2026-03-08 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability_type', models.CharField(choices=[('available', 'Dostępny'), ('service_trip', 'Wyjazd serwisowy'), ('installation', 'Montaż'), ('temporarily_unavailable', 'Niedostępny czasowo'), ('day_off', 'Dzień wolny'), ('vacation', 'Urlop'), ('sick_leave', 'Chorobowe')], db_index=True, max_length=30, verbose_name='typ dostępności')),
                ('date', models.DateField(db_index=True, verbose_name='data')),
                ('is_all_day', models.BooleanField(default=True, help_text='Jeśli True, wpis dotyczy całego dnia; w przeciwnym razie używane są start_time i end_time', verbose_name='cały dzień')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='godzina rozpoczęcia')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='godzina zakończenia')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='notatka')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktywny')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_entries', to=settings.AUTH_USER_MODEL, verbose_name='utworzył')),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['staff', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_entries', to=settings.AUTH_USER_MODEL, verbose_name='pracownik')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_availability_entries', to=settings.AUTH_USER_MODEL, verbose_name='zaktualizował')),
            ],
            options={
                'verbose_name': 'dostępność pracownika',
                'verbose_name_plural': 'dostępności pracowników',
                'ordering': ['date', 'employee', 'start_time'],
                'indexes': [models.Index(fields=['date', 'employee'], name='availabilit_date_fddc21_idx'), models.Index(fields=['employee', 'date'], name='availabilit_employe_6aacf9_idx')],
            },
        ),
    ]
