# Generated by Django 5.1.15 on 2026-04-03 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAbsenceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availability_type', models.CharField(choices=[('day_off', 'Dzień wolny'), ('vacation', 'Urlop')], db_index=True, max_length=30, verbose_name='typ nieobecności')),
                ('start_date', models.DateField(db_index=True, verbose_name='data od')),
                ('end_date', models.DateField(db_index=True, verbose_name='data do')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='notatka')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('approved', 'Zaakceptowane'), ('rejected', 'Odrzucone')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='zweryfikowano o')),
                ('review_note', models.CharField(blank=True, max_length=300, verbose_name='komentarz admina')),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['staff', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='absence_requests', to=settings.AUTH_USER_MODEL, verbose_name='pracownik')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_absence_requests', to=settings.AUTH_USER_MODEL, verbose_name='zweryfikował')),
            ],
            options={
                'verbose_name': 'zgłoszenie nieobecności',
                'verbose_name_plural': 'zgłoszenia nieobecności',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date'], name='availabilit_status_584dcc_idx'), models.Index(fields=['employee', 'status'], name='availabilit_employe_be3272_idx')],
            },
        ),
    ]
