# Generated by Django 5.1.15 on 2026-04-05 13:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0002_employeeabsencerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='rozpoczęto')),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='zakończono')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='czas pracy w sekundach')),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['staff', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='pracownik')),
            ],
            options={
                'verbose_name': 'sesja pracy',
                'verbose_name_plural': 'sesje pracy',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['employee', 'started_at'], name='availabilit_employe_ff6075_idx'), models.Index(fields=['employee', 'ended_at'], name='availabilit_employe_07df24_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('employee',), name='uniq_open_work_session_per_employee')],
            },
        ),
    ]
