# Generated by Django 5.1.7 on 2026-03-07 22:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0002_add_payment_internal_status_source_estimated_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HammerGlassFilmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
            ],
            options={
                'verbose_name': 'typ folii Hammer Glass',
                'verbose_name_plural': 'typy folii Hammer Glass',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HammerGlassProduct',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nazwa')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='SKU / kod')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cena')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hammer_glass/%Y/%m/', verbose_name='zdjęcie')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('compatible_device_categories', models.JSONField(blank=True, default=list, help_text='Lista: phone, tablet, smartwatch, laptop, other. Pusta = wszystkie.', verbose_name='kategorie urządzeń')),
                ('film_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='hammer_glass.hammerglassfilmtype', verbose_name='typ folii')),
            ],
            options={
                'verbose_name': 'produkt Hammer Glass',
                'verbose_name_plural': 'produkty Hammer Glass',
                'ordering': ['film_type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RepairHammerGlassOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='ilość')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, help_text='Kopia ceny produktu w chwili oferty', max_digits=10, verbose_name='cena jedn. w momencie oferty')),
                ('offered_at', models.DateTimeField(auto_now_add=True, verbose_name='data oferty')),
                ('accepted', models.BooleanField(default=False, verbose_name='zaakceptowane przez klienta')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='data akceptacji')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='notatka')),
                ('offered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hammer_glass_offers_made', to=settings.AUTH_USER_MODEL, verbose_name='oferował')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_offers', to='hammer_glass.hammerglassproduct', verbose_name='produkt (folia)')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hammer_glass_offers', to='repairs.repairrequest', verbose_name='naprawa')),
            ],
            options={
                'verbose_name': 'oferta Hammer Glass przy naprawie',
                'verbose_name_plural': 'oferty Hammer Glass przy naprawach',
                'ordering': ['-offered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hammerglassproduct',
            index=models.Index(fields=['is_active'], name='hammer_glas_is_acti_c2dad0_idx'),
        ),
        migrations.AddIndex(
            model_name='hammerglassproduct',
            index=models.Index(fields=['film_type', 'is_active'], name='hammer_glas_film_ty_5a228d_idx'),
        ),
        migrations.AddIndex(
            model_name='repairhammerglassoffer',
            index=models.Index(fields=['repair'], name='hammer_glas_repair__b41938_idx'),
        ),
        migrations.AddIndex(
            model_name='repairhammerglassoffer',
            index=models.Index(fields=['accepted'], name='hammer_glas_accepte_aba069_idx'),
        ),
    ]
