# Generated by Django 5.1.7 on 2026-03-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_glass', '0001_initial_hammer_glass'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammerglassproduct',
            name='features',
            field=models.CharField(blank=True, max_length=200, verbose_name='cechy'),
        ),
        migrations.AddField(
            model_name='hammerglassproduct',
            name='protection_level',
            field=models.CharField(blank=True, choices=[('wysoka', 'wysoka'), ('bardzo_wysoka', 'bardzo wysoka'), ('premium', 'premium')], db_index=True, max_length=20, verbose_name='poziom ochrony'),
        ),
    ]
