# Generated by Django 5.1.7 on 2026-03-07 21:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='imię')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nazwisko')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefon')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Pracownik serwisu'), ('client', 'Klient')], default='client', max_length=10, verbose_name='rola')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('is_staff', models.BooleanField(default=False, verbose_name='dostęp do panelu admina')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data rejestracji')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='ostatnie logowanie')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'użytkownik',
                'verbose_name_plural': 'użytkownicy',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='stanowisko')),
                ('bio', models.TextField(blank=True, verbose_name='opis')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='staff/avatars/', verbose_name='zdjęcie')),
                ('is_available', models.BooleanField(default=True, verbose_name='dostępny do przypisania')),
                ('total_repairs', models.PositiveIntegerField(default=0, verbose_name='łączna liczba napraw')),
                ('active_repairs', models.PositiveIntegerField(default=0, verbose_name='aktywne naprawy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'profil pracownika',
                'verbose_name_plural': 'profile pracowników',
            },
        ),
    ]
