# Generated by Django 5.1.7 on 2026-03-07 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('login_status', models.CharField(choices=[('success', 'Sukces'), ('failed', 'Niepowodzenie')], max_length=20, verbose_name='status')),
                ('logged_in_at', models.DateTimeField(auto_now_add=True, verbose_name='data logowania')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'log logowania',
                'verbose_name_plural': 'logi logowań',
                'ordering': ['-logged_in_at'],
            },
        ),
    ]
