# Generated by Django 6.0.2 on 2026-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staff_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffnotification',
            new_name='accounts_st_user_id_f9eb1e_idx',
            old_name='accounts_st_user_id_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='staffnotification',
            new_name='accounts_st_user_id_e65914_idx',
            old_name='accounts_st_user_id_9b2c3d_idx',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='accepts_shipment_repairs',
            field=models.BooleanField(default=True, help_text='Czy pracownik może być przypisywany do napraw wysyłkowych', verbose_name='przyjmuje naprawy wysyłkowe'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False, help_text='Konto nie może być usunięte; służy do odzyskania systemu', verbose_name='superadministrator'),
        ),
    ]
