# Generated by Django 6.0.2 on 2026-03-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staff_management_and_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Po zalogowaniu użytkownik zostanie przekierowany do zmiany hasła', verbose_name='wymuś zmianę hasła przy pierwszym logowaniu'),
        ),
    ]
