# Generated by Django 5.1.15 on 2026-03-15 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Klient: po weryfikacji kodem OTP z e-maila', verbose_name='e-mail zweryfikowany'),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='kod')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ważny do')),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='błędne próby')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'kod weryfikacji e-mail',
                'verbose_name_plural': 'kody weryfikacji e-mail',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='accounts_em_user_id_764691_idx')],
            },
        ),
    ]
