# Generated by Django 5.1.15 on 2026-03-15 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_email_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='wysłano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_send_logs', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'log wysyłki kodu weryfikacji',
                'verbose_name_plural': 'logi wysyłki kodu weryfikacji',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', '-sent_at'], name='accounts_em_user_id_46a2de_idx')],
            },
        ),
    ]
