# Generated by Django 5.1.15 on 2026-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_verification_send_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45, verbose_name='adres IP')),
                ('email_lower', models.CharField(db_index=True, max_length=255, verbose_name='e-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data')),
            ],
            options={
                'verbose_name': 'log nieudanego logowania',
                'verbose_name_plural': 'logi nieudanych logowań',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', '-created_at'], name='accounts_lo_ip_addr_265e94_idx'), models.Index(fields=['email_lower', '-created_at'], name='accounts_lo_email_l_64323b_idx')],
            },
        ),
    ]
