# Generated by Django 5.1.15 on 2026-03-15 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_login_failure_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_blocked_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Po 5 błędnych kodach OTP — blokada 15 min.', null=True, verbose_name='weryfikacja zablokowana do'),
        ),
        migrations.CreateModel(
            name='EmailVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=255, verbose_name='e-mail')),
                ('ip_address', models.CharField(blank=True, max_length=45, verbose_name='adres IP')),
                ('success', models.BooleanField(default=False, verbose_name='sukces')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_attempts', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'próba weryfikacji e-mail',
                'verbose_name_plural': 'próby weryfikacji e-mail',
                'ordering': ['-created_at'],
            },
        ),
    ]
