# Generated by Django 5.1.15 on 2026-03-15 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_verification_attempt_and_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='ważny do')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'token resetu hasła',
                'verbose_name_plural': 'tokeny resetu hasła',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'expires_at'], name='accounts_pa_token_3afc1d_idx')],
            },
        ),
    ]
