# Generated by Django 5.1.15 on 2026-04-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffnotification_uuid_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('phone_tablet', 'Telefony, Tablety, Smartwatche'), ('laptop_printer', 'Laptopy, komputery, konsole, drukarki'), ('general', 'Ogólne / proste naprawy')], db_index=True, max_length=30, verbose_name='specjalizacja'),
        ),
    ]
