# Generated by Django 5.1.7 on 2026-03-07 21:23

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='nazwa marki')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('logo', models.FileField(blank=True, null=True, upload_to='brands/logos/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, help_text='Czy marka jest aktualnie obsługiwana', verbose_name='aktywna')),
                ('description', models.TextField(blank=True, help_text='Opis marki dla celów marketingowych', verbose_name='opis')),
            ],
            options={
                'verbose_name': 'marka',
                'verbose_name_plural': 'marki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('phone', 'Telefon'), ('tablet', 'Tablet'), ('smartwatch', 'Smartwatch'), ('laptop', 'Laptop'), ('desktop', 'Komputer stacjonarny'), ('printer', 'Drukarka'), ('console', 'Konsola'), ('data_recovery', 'Odzyskiwanie danych'), ('other', 'Inne')], max_length=20, verbose_name='kategoria')),
                ('model_name', models.CharField(blank=True, help_text='Jeśli model nie jest w bazie', max_length=200, verbose_name='nazwa modelu (ręcznie)')),
                ('serial_number', models.CharField(blank=True, max_length=100, validators=[apps.common.validators.validate_serial_number], verbose_name='numer seryjny')),
                ('imei', models.CharField(blank=True, help_text='Dotyczy telefonów i tabletów z LTE', max_length=20, validators=[apps.common.validators.validate_imei], verbose_name='IMEI')),
                ('condition_on_arrival', models.TextField(blank=True, help_text='Opis stanu wizualnego, uszkodzeń mechanicznych itp.', verbose_name='stan przy przyjęciu')),
                ('has_screen_protector', models.BooleanField(default=False, verbose_name='posiada folię ochronną')),
                ('has_case', models.BooleanField(default=False, verbose_name='posiada etui/case')),
                ('accessories_included', models.TextField(blank=True, help_text="np. 'ładowarka, kabel USB-C, słuchawki'", verbose_name='dołączone akcesoria')),
                ('password', models.CharField(blank=True, help_text='Hasło dostępu do urządzenia (jeśli podane)', max_length=100, verbose_name='hasło/PIN/kod')),
                ('notes', models.TextField(blank=True, help_text='Dodatkowe informacje o urządzeniu', verbose_name='notatki')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.brand', verbose_name='marka')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='clients.client', verbose_name='klient')),
            ],
            options={
                'verbose_name': 'urządzenie',
                'verbose_name_plural': 'urządzenia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('image', models.FileField(upload_to='devices/photos/%Y/%m/', verbose_name='zdjęcie')),
                ('caption', models.CharField(blank=True, help_text="np. 'uszkodzony ekran', 'zarysowania na tylnej klapce'", max_length=200, verbose_name='opis')),
                ('is_before', models.BooleanField(default=True, verbose_name='zdjęcie przed naprawą')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='devices.device', verbose_name='urządzenie')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_images', to=settings.AUTH_USER_MODEL, verbose_name='dodane przez')),
            ],
            options={
                'verbose_name': 'zdjęcie urządzenia',
                'verbose_name_plural': 'zdjęcia urządzeń',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('category', models.CharField(choices=[('phone', 'Telefon'), ('tablet', 'Tablet'), ('smartwatch', 'Smartwatch'), ('laptop', 'Laptop'), ('desktop', 'Komputer stacjonarny'), ('printer', 'Drukarka'), ('console', 'Konsola'), ('data_recovery', 'Odzyskiwanie danych'), ('other', 'Inne')], max_length=20, verbose_name='kategoria')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='nazwa modelu')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('full_name', models.CharField(blank=True, help_text="np. 'Apple iPhone 13 Pro Max 256GB Sierra Blue'", max_length=300, verbose_name='pełna nazwa')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='rok wydania')),
                ('processor', models.CharField(blank=True, max_length=200, verbose_name='procesor')),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='RAM')),
                ('storage_options', models.CharField(blank=True, help_text="np. '64GB, 128GB, 256GB'", max_length=200, verbose_name='opcje pamięci')),
                ('image', models.FileField(blank=True, null=True, upload_to='devices/models/', verbose_name='zdjęcie')),
                ('is_active', models.BooleanField(default=True, help_text='Czy model jest aktualnie serwisowany', verbose_name='aktywny')),
                ('popularity_score', models.PositiveIntegerField(default=0, help_text='Aktualizowany na podstawie liczby napraw', verbose_name='wskaźnik popularności')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='devices.brand', verbose_name='marka')),
            ],
            options={
                'verbose_name': 'model urządzenia',
                'verbose_name_plural': 'modele urządzeń',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(blank=True, help_text='Wybierz z listy lub zostaw puste jeśli nie ma w bazie', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicemodel', verbose_name='model'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['category'], name='devices_dev_categor_775f51_idx'),
        ),
        migrations.AddIndex(
            model_name='devicemodel',
            index=models.Index(fields=['-popularity_score'], name='devices_dev_popular_890923_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemodel',
            unique_together={('brand', 'name')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['client', '-created_at'], name='devices_dev_client__933129_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['category'], name='devices_dev_categor_449372_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='devices_dev_serial__4a3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['imei'], name='devices_dev_imei_94ab30_idx'),
        ),
    ]
