# Generated by Django 6.0.2 on 2026-03-08 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_initial_orders_module'),
        ('orders', '0002_spec_ean_repair_supply_manual'),
        ('repairs', '0012_repair_image_type_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='tytuł')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W trakcie'), ('waiting', 'Czeka'), ('completed', 'Wykonane'), ('cancelled', 'Anulowane')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('standard', 'Standardowy'), ('important', 'Ważny'), ('urgent', 'Pilny')], db_index=True, default='standard', max_length=20, verbose_name='priorytet')),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='termin wykonania')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='data zakończenia')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='zarchiwizowane')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='przypisane do')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='utworzył')),
                ('related_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='clients.client', verbose_name='powiązany klient')),
                ('related_customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='orders.customerorder', verbose_name='powiązane zamówienie klienta')),
                ('related_repair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='repairs.repairrequest', verbose_name='powiązana naprawa')),
                ('related_store_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_tasks', to='orders.storesupplyorder', verbose_name='powiązane zamówienie sklepowe')),
            ],
            options={
                'verbose_name': 'zadanie',
                'verbose_name_plural': 'zadania',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='treść')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='zadanie')),
            ],
            options={
                'verbose_name': 'komentarz do zadania',
                'verbose_name_plural': 'komentarze do zadań',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status', '-due_date'], name='tasks_task_assigne_bb025d_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='tasks_task_due_dat_3f7773_idx'),
        ),
    ]
