# Generated by Django 5.1.7 on 2026-03-07 21:23

import apps.common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='usunięty')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='data usunięcia')),
                ('client_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='numer klienta')),
                ('first_name', models.CharField(max_length=100, verbose_name='imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(db_index=True, max_length=20, validators=[apps.common.validators.validate_polish_phone], verbose_name='telefon')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='ulica')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='miasto')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='kod pocztowy')),
                ('country', models.CharField(blank=True, default='Polska', max_length=100, verbose_name='kraj')),
                ('preferred_contact', models.CharField(choices=[('phone', 'Telefon'), ('email', 'E-mail'), ('sms', 'SMS'), ('panel', 'Panel klienta')], default='email', max_length=20, verbose_name='preferowany sposób kontaktu')),
                ('accepts_marketing', models.BooleanField(default=False, verbose_name='akceptuje komunikację marketingową')),
                ('internal_notes', models.TextField(blank=True, help_text='Notatki widoczne tylko dla staff', verbose_name='notatki wewnętrzne')),
                ('total_repairs', models.PositiveIntegerField(default=0, verbose_name='całkowita liczba napraw')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='całkowita kwota wydana')),
                ('is_vip', models.BooleanField(default=False, help_text='Klient priorytetowy', verbose_name='klient VIP')),
                ('is_blacklisted', models.BooleanField(default=False, help_text='Klient problematyczny', verbose_name='na czarnej liście')),
                ('user', models.OneToOneField(blank=True, help_text='Jeśli klient ma konto w systemie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='konto użytkownika')),
            ],
            options={
                'verbose_name': 'klient',
                'verbose_name_plural': 'klienci',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="np. 'Dom', 'Praca', 'Wysyłkowy'", max_length=50, verbose_name='etykieta')),
                ('street', models.CharField(max_length=200, verbose_name='ulica i numer')),
                ('city', models.CharField(max_length=100, verbose_name='miasto')),
                ('postal_code', models.CharField(max_length=10, verbose_name='kod pocztowy')),
                ('country', models.CharField(default='Polska', max_length=100, verbose_name='kraj')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_polish_phone], verbose_name='telefon kontaktowy')),
                ('additional_info', models.TextField(blank=True, help_text='np. kod bramy, piętro', verbose_name='dodatkowe informacje')),
                ('is_default', models.BooleanField(default=False, verbose_name='domyślny adres')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client', verbose_name='klient')),
            ],
            options={
                'verbose_name': 'adres klienta',
                'verbose_name_plural': 'adresy klientów',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientConsent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('contact', 'Zgoda na kontakt'), ('terms', 'Akceptacja regulaminu'), ('diagnostics', 'Zgoda na diagnozę'), ('repair', 'Zgoda na naprawę'), ('shipping', 'Zgoda na warunki wysyłki'), ('marketing', 'Zgoda marketingowa'), ('data_processing', 'Zgoda na przetwarzanie danych')], max_length=30, verbose_name='typ zgody')),
                ('is_granted', models.BooleanField(default=False, verbose_name='zgoda udzielona')),
                ('consent_text', models.TextField(help_text='Dokładna treść zgody pokazana klientowi', verbose_name='treść zgody')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='data udzielenia')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='data cofnięcia')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clients.client', verbose_name='klient')),
            ],
            options={
                'verbose_name': 'zgoda klienta',
                'verbose_name_plural': 'zgody klientów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(verbose_name='treść notatki')),
                ('is_important', models.BooleanField(default=False, help_text='Oznacz jako ważną aby wyróżnić', verbose_name='ważna notatka')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client', verbose_name='klient')),
            ],
            options={
                'verbose_name': 'notatka o kliencie',
                'verbose_name_plural': 'notatki o klientach',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'phone'], name='clients_cli_email_5a39e6_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_number'], name='clients_cli_client__d84143_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='clients_cli_created_552574_idx'),
        ),
        migrations.AddIndex(
            model_name='clientconsent',
            index=models.Index(fields=['client', 'consent_type'], name='clients_cli_client__190ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientconsent',
            index=models.Index(fields=['-created_at'], name='clients_cli_created_ee023f_idx'),
        ),
    ]
