# Generated by Django 5.1.7 on 2026-03-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('compliance', '0001_initial_gdpr_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientconsent',
            name='terms_version',
            field=models.ForeignKey(blank=True, help_text='Opcjonalnie: wersja regulaminu przy tej zgodzie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='compliance.termsversion', verbose_name='wersja dokumentu'),
        ),
    ]
