# Generated by Django 6.0.2 on 2026-03-08 10:48

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial_gdpr_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_segment',
            field=models.CharField(blank=True, choices=[('new', 'Nowy klient'), ('returning', 'Klient powracający'), ('regular', 'Klient stały'), ('premium', 'Klient premium'), ('business', 'Klient biznesowy')], db_index=True, default='new', max_length=20, verbose_name='segment klienta'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Osoba prywatna'), ('business', 'Firma')], db_index=True, default='individual', max_length=20, verbose_name='typ klienta'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail firmowy'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='nazwa firmy'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, validators=[apps.common.validators.validate_polish_phone], verbose_name='telefon firmowy'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, verbose_name='osoba kontaktowa'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_visit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ostatnia wizyta'),
        ),
        migrations.AddField(
            model_name='client',
            name='nip',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='client',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, help_text='Liczba przyjęć / napraw (do badge „klient wraca”)', verbose_name='liczba wizyt'),
        ),
    ]
