# Generated by Django 6.0.2 on 2026-03-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_type_segment_and_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefon firmowy'),
        ),
    ]
