# Generated by Django 5.1.7 on 2026-03-07 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0002_add_payment_internal_status_source_estimated_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='data aktualizacji')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='nazwa szablonu')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('panel', 'Panel klienta'), ('phone', 'Telefon'), ('internal', 'Wewnętrzna')], max_length=10, verbose_name='kanał')),
                ('message_type', models.CharField(choices=[('info', 'Informacyjna'), ('quote', 'Wycena'), ('status_update', 'Aktualizacja statusu'), ('question', 'Pytanie'), ('answer', 'Odpowiedź'), ('reminder', 'Przypomnienie'), ('internal_note', 'Notatka wewnętrzna')], default='info', max_length=20, verbose_name='typ wiadomości')),
                ('subject', models.CharField(blank=True, help_text='Tylko dla kanału e-mail; może zawierać {{zmienne}}', max_length=200, verbose_name='temat')),
                ('body', models.TextField(help_text='Zmienne: {{repair_number}}, {{client_name}}, {{device_name}}, {{status}}, {{estimated_duration}}', verbose_name='treść')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='kolejność')),
                ('suggested_for_status', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='sugerowany przy statusie')),
            ],
            options={
                'verbose_name': 'szablon wiadomości',
                'verbose_name_plural': 'szablony wiadomości',
                'ordering': ['channel', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['channel', 'is_active'], name='communicati_channel_0c1419_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('panel', 'Panel klienta'), ('phone', 'Telefon'), ('internal', 'Wewnętrzna')], max_length=10, verbose_name='kanał')),
                ('recipient', models.CharField(help_text='Adres e-mail lub numer telefonu', max_length=200, verbose_name='odbiorca')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='temat')),
                ('body_snapshot', models.TextField(help_text='Kopia treści w momencie wysyłki', verbose_name='wysłana treść')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='wysłano')),
                ('status', models.CharField(choices=[('sent', 'Wysłano'), ('failed', 'Błąd wysyłki')], default='sent', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='komunikat błędu')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='repairs.repairrequest', verbose_name='naprawa')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL, verbose_name='wysłał')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_logs', to='communications.messagetemplate', verbose_name='szablon')),
            ],
            options={
                'verbose_name': 'log komunikacji',
                'verbose_name_plural': 'logi komunikacji',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['repair'], name='communicati_repair__b81fa9_idx'), models.Index(fields=['channel', 'sent_at'], name='communicati_channel_5e2086_idx')],
            },
        ),
    ]
