# Generated by Django 5.1.7 on 2026-03-07 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GdprRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('export', 'Eksport danych'), ('deletion', 'Usunięcie danych / konta')], max_length=20, verbose_name='typ wniosku')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('in_progress', 'W realizacji'), ('completed', 'Zrealizowano'), ('rejected', 'Odrzucono')], default='pending', max_length=20, verbose_name='status')),
                ('reason', models.TextField(blank=True, verbose_name='powód / uwagi klienta')),
                ('resolution_note', models.TextField(blank=True, help_text='Wewnętrzna notatka przy realizacji', verbose_name='notatka do rozstrzygnięcia')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='data wniosku')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='data rozstrzygnięcia')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_requests', to='clients.client', verbose_name='klient')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdpr_requests_handled', to=settings.AUTH_USER_MODEL, verbose_name='rozstrzygnął')),
            ],
            options={
                'verbose_name': 'wniosek RODO',
                'verbose_name_plural': 'wnioski RODO',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='np. REGULAMIN_2024', max_length=50, verbose_name='kod')),
                ('version', models.CharField(max_length=30, verbose_name='wersja')),
                ('document_type', models.CharField(choices=[('terms', 'Regulamin'), ('privacy', 'Polityka prywatności'), ('other', 'Inny')], max_length=50, verbose_name='typ dokumentu')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywna')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='data publikacji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data utworzenia')),
            ],
            options={
                'verbose_name': 'wersja dokumentu',
                'verbose_name_plural': 'wersje dokumentów',
                'ordering': ['-published_at', '-created_at'],
                'unique_together': {('code', 'version')},
            },
        ),
    ]
