# Generated by Django 5.1.7 on 2026-03-07 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial_gdpr_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('database', 'Baza danych'), ('media', 'Pliki media'), ('full', 'Pełny')], max_length=50, verbose_name='typ')),
                ('status', models.CharField(choices=[('started', 'Rozpoczęto'), ('success', 'Sukces'), ('failed', 'Błąd')], max_length=20, verbose_name='status')),
                ('storage_path', models.CharField(blank=True, max_length=500, verbose_name='ścieżka / URI')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='rozpoczęto')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='zakończono')),
                ('error_message', models.TextField(blank=True, verbose_name='komunikat błędu')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_logs', to=settings.AUTH_USER_MODEL, verbose_name='wywołany przez')),
            ],
            options={
                'verbose_name': 'log backupu',
                'verbose_name_plural': 'logi backupów',
                'ordering': ['-started_at'],
            },
        ),
    ]
