# Generated by Django 5.1.7 on 2026-04-03 00:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_add_backup_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("setting", "Ustawienie"), ("feature_flag", "Feature flag")],
                        db_index=True,
                        max_length=20,
                        verbose_name="typ encji",
                    ),
                ),
                ("entity_key", models.CharField(db_index=True, max_length=120, verbose_name="klucz encji")),
                ("action", models.CharField(default="updated", max_length=30, verbose_name="akcja")),
                ("old_value", models.JSONField(blank=True, null=True, verbose_name="stara wartość")),
                ("new_value", models.JSONField(blank=True, null=True, verbose_name="nowa wartość")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="metadane")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="utworzono")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="zmienił",
                    ),
                ),
            ],
            options={
                "verbose_name": "log audytu konfiguracji",
                "verbose_name_plural": "logi audytu konfiguracji",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=80, unique=True, verbose_name="klucz")),
                ("name", models.CharField(max_length=120, verbose_name="nazwa")),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                ("is_enabled", models.BooleanField(default=False, verbose_name="włączona")),
                (
                    "rollout_percentage",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="0-100; pozwala etapowo uruchamiać funkcję.",
                        validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                        verbose_name="rollout %",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="zaktualizowano")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="utworzono")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="zaktualizowane przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "flaga funkcji",
                "verbose_name_plural": "flagi funkcji",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(db_index=True, max_length=120, unique=True, verbose_name="klucz")),
                ("category", models.CharField(db_index=True, default="general", max_length=50, verbose_name="kategoria")),
                ("label", models.CharField(max_length=120, verbose_name="etykieta")),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "Tekst"),
                            ("integer", "Liczba całkowita"),
                            ("float", "Liczba zmiennoprzecinkowa"),
                            ("boolean", "Tak/Nie"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="typ wartości",
                    ),
                ),
                ("value_json", models.JSONField(blank=True, null=True, verbose_name="wartość")),
                ("is_secret", models.BooleanField(default=False, verbose_name="sekret")),
                ("is_readonly", models.BooleanField(default=False, verbose_name="tylko do odczytu")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="zaktualizowano")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="utworzono")),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_system_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="zaktualizowane przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "ustawienie systemowe",
                "verbose_name_plural": "ustawienia systemowe",
                "ordering": ["category", "key"],
            },
        ),
        migrations.AddIndex(
            model_name="configauditlog",
            index=models.Index(fields=["entity_type", "entity_key", "-created_at"], name="compliance__entity__6259a2_idx"),
        ),
    ]

